name: Build Backend

on:
  push:
    branches: [master]
    paths:
      - .github/workflows/**
      - backend/**
      - tools/**
  pull_request:
    branches: [master]
    paths:
      - .github/workflows/**
      - backend/**
      - tools/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.2

      - name: Install protoc-gen-go
        run: go get -u google.golang.org/protobuf/cmd/protoc-gen-go

      - name: Build protocol buffers code
        run: bash tools/protoc.sh . --no-js

        imports:

      - name: Run gofmt
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: fmt
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run go vet
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: vet
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run go vet with shadow
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: shadow
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run goimports
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: imports
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run golint
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: lint
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run staticcheck
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: staticcheck
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run errcheck
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: errcheck
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run gosec
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: sec
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: go build -v .
        working-directory: backend
