name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js v14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Build protocol buffers code
      run: bash ./tools/protoc.sh $(pwd) --no-golang

    - run: npm ci
    - run: npm run build
