name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v14.x
        uses: actions/setup-node@v2.3.1
        with:
          node-version: 14.x

      - uses: actions/cache@v2.1.6
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - uses: bahmutov/npm-install@v1

      - name: Build protocol buffers code
        run: bash ./tools/protoc.sh $(pwd) --no-golang

      - name: Lint
        run: npm run lint

      - name: Run next build
        run: npm run build
